### ISSUE TITLE
Getting an issue at the last step. Help!

### ISSUE THREAD

**Issue by DougPunchak** [Zerg00s/FlowPowerAppsMigrator#1]
This is the command window output.  
![image](https://user-images.githubusercontent.com/17028151/65791020-ddf3d300-e12e-11e9-93d6-f39e2f26ec16.png)

Text of the error: 
Converting SiteUrl ...Done.
ForEach-Object : The term 'resources[$i].newId' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by Zerg00s** [comment]
@DougPunchak, 

- This error shows up when one of the lists or libraries are missing in the destination site collection. 
- I have pushed an update that will make sure the script outputs the names of the missing lists.
- Can you download a new version and try running the script again?
