### ISSUE TITLE
SharePoint list not copying

### ISSUE THREAD

**Issue by teylyn** [Zerg00s/FlowPowerAppsMigrator#13]
I'm running the current version. I have a SharePoint list form customized with PA. I tick the list, but in the target site nothing changes. I've tried several times, starting with different situations in the target site, i.e.
-- The list exists with an old version of the form
-- the list exists with the SharePoint native form, no PowerApps
-- the list exists with no columns and no form
In all the above cases, the list remains exactly the same after running the code. Watching the PowerShell window, I see the following prompts
-- Extracting Template from https://something.com/sites/MySourceSite
--Applying template to https://something.com/sites/MySourceSite

It looks to me as if the template is extracted from the source site, but it is then not applied to the target site, but back to the source site. Can you check that?

**Comment by Zerg00s** [comment]
Hi @teylyn. Thank you. I will have a look at this bug in the next few days.

**Comment by KBolland** [comment]
Hi @Zerg00s ,

First of all thank you for this its going to be a great help.

I am trying the latest version and copying list and libraries but am getting on errors. I have attached an image of the output on the command.

Not sure if this is the same issue as teylyn has reported of if its another issue.

Are you able to advise.

Thanks 
[PowerApps Migration Test.pdf](https://github.com/Zerg00s/FlowPowerAppsMigrator/files/8060643/PowerApps.Migration.Test.pdf)

**Comment by Zerg00s** [comment]
Hi @KBolland,

Thank you for the screenshot. Based on what I see - there are no errors. These are merely warnings. I have uploaded a new release that makes these log messages clearer.

Do you have an issue when a list or a library not copied? If that's the case, can you tell me more about these lists and libraries?

**Comment by Zerg00s** [comment]
hi @teylyn and @KBolland. Sorry for the delay. I was able to replicate a bug on my end and fix it in the new release: https://github.com/Zerg00s/FlowPowerAppsMigrator/releases/tag/3.4

The lists were not copied to the target site due to a bug.

**Comment by KBolland** [comment]
Thanks so much @Zerg00s that solved the problem for us the lists are now creating as expecting and receive no error related to the copying. 

We have any issue possibly related to content type so I will paste that under the issue already raised regarding content type. 

But I am happy for you to close this issue from my end.

Thanks again.

**Comment by Zerg00s** [comment]
Thank you, @KBolland.
