### ISSUE TITLE
When I either double-click or run as administrator the Migrate-Packages.bat nothing happens

### ISSUE THREAD

**Issue by bob5bruce** [Zerg00s/FlowPowerAppsMigrator#14]
When I either double-click or run as administrator the Migrate-Packages.bat nothing happens after I press any key in the cmd.exe window.

![image](https://user-images.githubusercontent.com/74661757/152692100-b9e2f43a-d6bb-4788-adf8-3fbb4d1ddcf7.png)

The UI screens do not appear.

-Bob

**Comment by bob5bruce** [comment]
Nevermind I just read the red text.

**Comment by Zerg00s** [comment]
@bob5bruce Great! I'm glad you found the solution.
