### ISSUE TITLE
List Content

### ISSUE THREAD

**Issue by send2mark** [Zerg00s/FlowPowerAppsMigrator#18]
When it copies the list, should it also copay the content? If not, can that option be added?

**Comment by Zerg00s** [comment]
Hi @send2mark,

Currently the list contents are not copied. Perhaps, I can add it to a separate Move-Lists script.

Just out of curiosity, what kind of lists do you want to copy? If these are relatively simple, maybe you can copy the data using the grid view?

**Comment by send2mark** [comment]
It is a pretty simple list that I am testing with and I was thinking the same thing with copying the data. I was just wondering if I missed something. I have been looking for something like this for a while now. Thanks for sharing it!

**Comment by Zerg00s** [comment]
Thank you. 

You didn't miss anything. Flow and App Migrator does not support migration of list contents. It is not yet planned, but if it turns out a vital feature, perhaps, it can be done in the future.
