### ISSUE TITLE
List Views Not Migrated

### ISSUE THREAD

**Issue by C2C-Justin** [Zerg00s/FlowPowerAppsMigrator#22]
When SharePoint connectors are used in PowerAutomate, your tool does a great job of updating all the LIST Guids, but if the option "Limit Columns by View" is selected and a view is chosen, even if that view exists with the same name at the destination, the tool does not update those, we have to manually go in and fix these..
<img width="251" alt="WorkflowMigrationToolIssue1" src="https://user-images.githubusercontent.com/109986591/180851577-f4c33743-b986-4e15-8504-6448030d91ea.png">
.

**Comment by Zerg00s** [comment]
Hi @C2C-Justin. Interesting find. Thank you for taking time to report it with a screenshot. Let me have a look at it tonight. I remember I was working on moving the views but probably never ended up finish it. But your case shows that I need to make sure views are also migrated properly.

**Comment by C2C-Justin** [comment]
@Zerg00s , that would be fantastic.  I'd be willing to donate/tip on the project if that was available...

**Comment by Zerg00s** [comment]
Hi @C2C-Justin , I was able to update the Flow & App migrator to support views. Here is a new release: https://github.com/Zerg00s/FlowPowerAppsMigrator/releases/tag/3.6

I've tested it against one library and it seems to be working fine 😃

**Comment by C2C-Justin** [comment]
@Zerg00s I was able to download the newest version and try it out today.  It worked perfectly.  Thank you so much for the revision.
