### ISSUE TITLE
Migrate solution only without artifacts for incremental deployment

### ISSUE THREAD

**Issue by rohit404404** [Zerg00s/FlowPowerAppsMigrator#32]
This could be feature more than issue. I have below scenario

I used this tool and successfully moved solution from one tenant to another. Worked great.

I have small change in source power automate. I made that change. Next time i ran the tool, I did not want to migrate Sharepoint artifacts (since there is no change and it takes too much time). So , I did not select any list from popup and clicked ok. I expected, just new solution to be created without artifacts. However, i received below error. 

On side note, thanks a lot for creating this. Makes life so much easier!!! 

![image](https://user-images.githubusercontent.com/3784144/191670189-6763e970-4e45-43ab-8e86-89a73bb8f49c.png)

**Comment by Zerg00s** [comment]
hi @rohit404404,

In this case you can run the migrator with MIGRATE_LISTS set to False:

![image](https://user-images.githubusercontent.com/2797648/192678697-a5936d9e-2003-4aba-96aa-c23c6336f77f.png)

**Comment by rohit404404** [comment]
@Zerg00s Correct. However, will tool still go ahead and update list references from my src folder and generate new one in dist folder with destination listGUIDs? (assuming, lists are already available in destination) 
My confusion is, if I keep listMIgrate false, DIST folder generate solution , should not keep the reference to source site lists.

**Comment by Zerg00s** [comment]
Migration of list is completely optional: the guid mapping will be generated regardless. So the list references will still be updated in apps in flows even if you don't choose to migrate any lists.

**Comment by rohit404404** [comment]
Great. Perfect. Thank you @Zerg00s . Really appreciate your response.
