### ISSUE TITLE
Unable to login - Forbidden

### ISSUE THREAD

**Issue by tonjewaasjo** [Zerg00s/FlowPowerAppsMigrator#33]
I am a site collection admin on both sites and also a global admin on the tenant. This worked on the earlier version, but after the upgrade I did today, it hasn't worked. I got colleague of mine to log in with his user (FlowPowerAppsMigrator workes on his pc), but he got the same error.  Any suggestions? 
![Error](https://user-images.githubusercontent.com/50357862/191727199-db2c4a3d-fe6c-402a-b38c-63ead600a4b2.png)

**Comment by Zerg00s** [comment]
hi @tonjewaasjo If you already have enough permissions, try running the script with CLEAR_CREDENTIALS_CACHE set to True

**Comment by tonjewaasjo** [comment]
I downloaded that version and tried it. I get the message "⚠️  [Error] make sure you have FULL CONTROL at the source site: https://365nor.sharepoint.com/sites/HRAnsettelsesprosessnortura". The user is a SharePoint admin, and owner of the site collection. As mention before, a colleague of mine is using this on his computer and it works. When he tries on mine, it fails (he uses the same user). Can this error be anything else apart from rights?

**Comment by Zerg00s** [comment]
The issue might be related to the cached permissions. Perhaps the authentication window automatically logs you in in the source site. To make sure you are prompted to log in, try setting CLEAR_CREDENTIALS_CACHE to False when you run the migrator:

![image](https://user-images.githubusercontent.com/2797648/193131183-60057da9-bd78-43a2-b46d-bba7881bb9e8.png)

**Comment by tonjewaasjo** [comment]
That worked! Thanks a lot =)
