### ISSUE TITLE
Move-Lists.ps1 : You cannot call a method on a null-valued expression.

### ISSUE THREAD

**Issue by schullex** [Zerg00s/FlowPowerAppsMigrator#66]
When exporting lists following exception occurs:
Exporting lists and libraries...
Hidden fields count:
.......\FlowPowerAppsMigrator\MISC\Move-Lists.ps1 : You cannot call a method on a null-valued
expression.
At C:\Users\stefa\Downloads\FlowPowerAppsMigrator\RunAllScripts.ps1:98 char:5
+     . .\MISC\Move-Lists.ps1 -Path $Path -MigrationType Export -Source ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Move-Lists.ps1], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull,Move-Lists.ps1

**Comment by Zerg00s** [comment]
hi @schullex,

Thank you for creating an issue with the error details. And sorry for the delay. I just published a new release: https://github.com/Zerg00s/FlowPowerAppsMigrator/releases/tag/3.9.6

Would you be able to try it, please? I hope the issue should be resolved in this version.

**Comment by smithiu** [comment]
I am getting the same error as above, even with the newest release.

**Comment by Zerg00s** [comment]
Do you mind sharing your Lists.xml file, please?

**Comment by schullex** [comment]
I'm trying to migrate a solution which does not contain a Lists.xml. The migrator pulls the lists directly from the source site.

**Comment by Zerg00s** [comment]
hi @schullex,

The Lists.xml file is generated automatically during the migration process. All SharePoint lists pulled from the source site are saved to the Lists.xml file. If the export process is successful, this file should be located in the same folder with the .bat files:

![image](https://github.com/Zerg00s/FlowPowerAppsMigrator/assets/2797648/e8cbe115-a263-43ad-9df8-69a947a8c2c8)

Do you see this file in your Migrator folder?

**Comment by lordneeko** [comment]
@Zerg00s 
I have the same issue as well.  Can I send you my lists.xml file privately some how?

**Comment by lordneeko** [comment]
This may help @Zerg00s 
I noticed that after the error occured, when I look at the resourceMapping.csv
It doesn't have the "newId" column filled in
![image](https://github.com/Zerg00s/FlowPowerAppsMigrator/assets/11577533/306859e2-72fc-480f-9eac-1c7b26524878)


Might be irrelevant, and Maybe that doesn't happen until later in the script. Just thought I'd point it out.

**Comment by Zerg00s** [comment]
@lordneeko yes, please! Can you send me this XML file via a private message on LinkedIn? https://ca.linkedin.com/in/molodtsovd

**Comment by Zerg00s** [comment]
hi @lordneeko and @smithiu. Thank you for sharing the issue details and the Lists.xml file. I was able to reproduce and fix the issue in the latest release: https://github.com/Zerg00s/FlowPowerAppsMigrator/releases/tag/3.9.7

Would you please be able to check if this version works for you?

**Comment by lordneeko** [comment]
Running now. It appears that this issue is fixed.
