### ISSUE TITLE
Migrate customized list form from one site to another site in same tenant

### ISSUE THREAD

**Issue by hbsts** [Zerg00s/FlowPowerAppsMigrator#8]
Hi Denis,

is your tool supporting customized list forms, too? 

I used PnP Provisionig Engine to create the same list at another site. I customized the list form in the source, exported the package and used your tool to update the json files. Then I imported the zip package (create as new and updated the ressource name) in my tenant getting the error "An App already exists for this list. Remove the existing App before adding a new one." 

I checked the json file inside the zip package and the guid of the source list has been updated by the guid of the destination list.

If I perform this process again I am getting the error: "You have already created an application with this name. Please specify a different name. " 

But where is this application? The form is not bound to the destination list neither listed under Apps.

Do you have any ideas?

**Comment by hbsts** [comment]
As expected, your application is working perfectly. Seems to be a language related issue. Source and destination site need the same base language, I guess. Like with list and site templates. I was able to migrate a simple form from an english site to another english site. Anyway, the error message is annoying. Thanks for your time saving application!

**Comment by Zerg00s** [comment]
> As expected, your application is working perfectly. Seems to be a language related issue. Source and destination site need the same base language, I guess. Like with list and site templates. I was able to migrate a simple form from an english site to another english site. Anyway, the error message is annoying. Thanks for your time saving application!

Thank you! I am glad it works as expected. :)
