### ISSUE TITLE
RessourceMapping issue

### ISSUE THREAD

**Issue by holography-be** [Zerg00s/FlowPowerAppsMigrator#9]
Hi,

Maybe I'm wrong but seems in the script RunAllScripts, the line 65 must be after the import of the selected lists.
Is it correct ?

Best wishes for 2022

**Comment by holography-be** [comment]
Maybe like this ?

. .\GenerateInitialMapping.ps1
if ($MIGRATE_LISTS) {
    . .\MISC\Move-Lists.ps1 -Path $Path -MigrationType Export -SourceSite $SOURCE_SITE_URL
    . .\MISC\Move-Lists.ps1 -Path $Path -MigrationType Import -TargetSite $TARGET_SITE_URL	
}
. .\CompleteResourceMapping.ps1

**Comment by Zerg00s** [comment]
@holography-be thank you very much for calling it it out. I've just looked at it and I agree with you. I've just updated this code to include your suggestion.
